### ISSUE TITLE
Kerberos auth,go connect CDH hive  error  

### ISSUE THREAD

**Issue by hankkhan** [beltran/gohive#170]
"gosasl may have been installed without kerberos support please reinstall with `go get` using the flags `build kerberos`. Alternatively if `go run` is being ran it should be ran with `go run -tags kerberos ...` and the binary should have been build with `go build -tags kerberos"    No_gssapi will be called directly. What is the reason? Please answer, thank you very much

**Comment by beltran** [comment]
Hello, there are different auth mechanism (KERBEROS(Gssapi Sasl), NONE(Plain Sasl), LDAP, CUSTOM and NOSASL)  gohive can use with Apache Hive (or whatever the server is). Using the kerberos mechanism is more complicated than using the others because it requires libraries to be installed locally (see https://github.com/beltran/gohive#installation). In order to not make everyone who wants to use a non kerberos auth mechanism install these libraries locally, to build the client that's using kerberos auth a different tag is specified.

**Comment by hankkhan** [comment]
Thank you very much for replying to me, this is my step
1. yum install -y krb5-devel
2. go get -tags kerberos github.com/beltran/gohive
3. main.go:
     connection, errConn := gohive.Connect("hs2.example.com", 10000, "KERBEROS", configuration)
  4. go run main.go
Then it will go to sasl_trainsport.go line: 49
mechanism, err = gosasl.NewGSSAPIMechanism(configuration["service"])
Finally arrived
// NewGSSAPIMechanism returns a new GSSAPIMechanism
func NewGSSAPIMechanism(service string) (mechanism *GSSAPIMechanism, err error) {
panic(errorMsg)
}

Is it where I did not implement it? I can't find the reason, thank you! please help

**Comment by beltran** [comment]
Can you try running `go run --tags kerberos main.go` instead of `go run main.go`?

**Comment by hankkhan** [comment]
非常感谢！你是一个非常友好的技术大佬！

**Comment by beltran** [comment]
Happy to help
