### ISSUE TITLE
requests in several goroutines 

### ISSUE THREAD

**Issue by BogdanovDenis** [beltran/gohive#58]
In the standard library(database/sql), we have a pool of connections. Therefore, I can create a connection once and use it for all requests, even in several goroutines (it is convenient for mock testing). For example, using the MongoDB driver, I can also use one connection for all requests.

If I make one connection using your library and try to use it in several goroutines at the same time, I will get an error. Errors at each start can be different.

Can I use one connection(connection pool) for all queries in your library?

**Comment by beltran** [comment]
Sorry I missed this, this is not possible with this driver and as far as I know it's not possible given the protocol hive uses, there can't be several concurrent queries on the same connection.
This usually not a problem because hive doesn't execute as many concurrent queries as mongodb. The bottleneck hardly ever is the number of connections.
